name: Main_Branch_Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Version 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build Solution
        run: dotnet build Server_Side/Server_Side.sln

      - name: Restore NuGet packages
        run: dotnet restore Server_Side/Server_Side.sln

      - name: Run Unit Tests In DatabaseAnalysisModuleTests Folder
        run: dotnet test DatabaseAnalysisModuleTests/DatabaseAnalysisModuleTests.csproj

      - name: Run Unit Tests In AnalysisServiceTests Folder
        run: dotnet test AnalysisServiceTests/AnalysisServiceTests.csproj

      - name: Publish Test Results DatabaseAnalysisModuleTests Folder
        uses: actions/upload-artifact@v2
        with:
          name: test-results-database
          path: DatabaseAnalysisModuleTests/TestResults

      - name: Publish Test Results AnalysisServiceTests Folder
        uses: actions/upload-artifact@v2
        with:
          name: test-results-analysis
          path: AnalysisServiceTests/TestResults