name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Restore
        run: dotnet restore ./Server_Side/Server_Side.sln

      - name: Build
        run: dotnet build ./Server_Side/Server_Side.sln --configuration Release --no-restore

      - name: Run Unit Tests In DatabaseAnalysisModuleTests Folder
        run: dotnet test DatabaseAnalysisModuleTests/DatabaseAnalysisModuleTests.csproj

      - name: Run Unit Tests In AnalysisServiceTests Folder
        run: dotnet test AnalysisServiceTests/AnalysisServiceTests.csproj

      - name: Publish Test Results DatabaseAnalysisModuleTests Folder
        uses: actions/upload-artifact@v2
        with:
          name: test-results-database
          path: DatabaseAnalysisModuleTests/TestResults

      - name: Publish Test Results AnalysisServiceTests Folder
        uses: actions/upload-artifact@v2
        with:
          name: test-results-analysis
          path: AnalysisServiceTests/TestResults
